baseURL = "https://zahidur59.github.io/hugoTestbed/"
languageCode = "en-us"
title = "Hugo Testbed"
publishDir = "docs"

paginate = 5

[outputs]
  home = ["html", "json"]

[menu]

    [[menu.main]]
    name = "Home"
    title = "Welcome to our site"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/"
    weight = 1
   
    [[menu.main]]
    name = "Products"
    title = "Check out what we have for you"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/products/"
    weight = 2
    
    [[menu.main]]
    name = "News/Events"
    title = "Checkout whats happening with us"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/event_posts/"
    weight = 3
    
    [[menu.main]]
    identifier = "about"
    name = "About us"
    title = "About our company"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 4
    
    [[menu.main]]
    name = "Contact Us"
    title = "Feel free to contact us"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/contact/"
    weight = 5
